-- @noindex

ICONS = {
    ['BOX'] = 'A',
    ['BRIEFCASE'] = 'B',
    ['PENCIL'] = 'C',
    ['DOCK_DOWN'] = 'D',
    ['UNDOCK'] = 'E',
    ['FOLDER'] = 'f',
    ['ARROW_LEFT'] = 'F',
    ['GEAR'] = 'G',
    ['HEADPHONES'] = 'H',
    ['COMPUTER'] = 'I',
    ['DISK'] = 'K',
    ['LEFT'] = 'L',
    ['MONEY'] = 'M',
    ['MINUS'] = 'N',
    ['POLARITY'] = 'O',
    ['PLUS'] = 'P',
    ['RIGHT'] = 'R',
    ['SUBFOLDER'] = 's',
    ['STAR'] = 'S',
    ['TRASH'] = 'T',
    ['UNDO'] = 'U',
    ['ENVELOPE'] = 'V',
    ['ARROW_RIGHT'] = 'W',
    ['CLOSE'] = 'X',
    ['STEREO'] = 'Y',
    ['MONO'] = 'Z',
    ['SEARCH'] = '*',
    ['TAG'] = '-',
    ['QUESTION'] = '?'
}