-- @noindex

---------------------------------------
-- THOUGHTS and TODOS -----------------
---------------------------------------

-- DONE: Add presets to userdata import/export
-- DONE: Create actions for presets/filters
-- DONE: Reset filter button
-- DONE: Better visual representation of search mode
-- DONE: Option to hide sidebar
-- DONE: do something about horizontal scroll for long results
-- DONE: Settings window
-- DONE: Add project templates
-- DONE: Add markers/regions
-- DONE: Think of a way to handle execution of multiple items together rather than sequentially (but not always - example: multiple track selection VS run actions sequentially)
-- DONE: Refresh project specific assets (tracks, markers/regions)
-- DONE: Fix Hints
-- DONE: Randomly execute one result
-- DONE: Track newly added plugins
-- DONE: All execute functions
-- DONE: handle FX instruments
-- DONE: fix resizing settings and help windows
-- DONE: Handle hints for selection that spans many asset types
-- DONE: minimal mode
-- DONE: Settings window - add Convert Folders/Categories to tags
-- DONE: Import progress bar (coroutine?)
-- DONE: Add recent Projects
-- DONE: Quick Chain - only accept FX and FX Chains
-- DONE: Quick Chain - drag to objects, tracks and blank
-- DONE: Quick Chain
-- DONE: Setting to override default send volume
-- DONE: Docking
-- DONE: xd
-- TODO: Setting to show/hide hidden tracks
-- TODO: Create Default Presets with Magic Words for types
-- TODO: Show Total Results
-- TODO: write help
-- TODO: Test on windows
-- TODO: Zoom scroll issue is still there (eg. at 76% but not just)
---------------------------------------
-- AFTER LAUNCH -----------------------
---------------------------------------

-- Some asset types make no sense in multiple selections (markers/regions/projects/project templates). Make selecting them impossible via a switch in their assetType so that it is more robust.

---------------------------------------
-- MAYBE LATER ------------------------
---------------------------------------

-- disable selecting multiple filters of the same type? (this is a petty one)
-- Add tooltips to results with additional information? (no. Maybe think of another way to show all info about an asset?)
-- Refresh projects? (not for now)