-- @noindex

---------------------------------------
-- THOUGHTS and TODOS -----------------
---------------------------------------

-- DONE: Add presets to userdata import/export
--       ✓ FX Folder filters: exported as-is, validated at runtime
--       ✓ Category filters: exported as-is, validated at runtime  
--       ✓ Developer filters: exported as-is, validated at runtime
--       ✓ Tag filters: validate that referenced tags exist during import, skip preset if any tag missing
--       ✓ Search text filters: imported as-is (safe)
--       ✓ Import order: tags imported before presets to ensure tag dependencies are met
--       ✓ Provide clear warnings about which presets were skipped and why (missing tags)
--       ✓ Presets section added to export/import file format with serialized filter data
--       ✓ Merge mode support for presets (preserve existing + add new)
--       ✓ UI labels updated to include presets in export/import dialogs
-- DONE: Create actions for presets/filters
-- DONE: Reset filter button
-- DONE: Better visual representation of search mode
-- DONE: Option to hide sidebar
-- DONE: do something about horizontal scroll for long results
-- DONE: Settings window
-- DONE: Add project templates
-- DONE: Add markers/regions
-- TODO: All execute functions + handling FX instruments
-- TODO: Create Default Presets with Magic Words for types
-- TODO: Fix Hints
-- TODO: Add tooltips to results with additional information
-- TODO: Refresh tracks
-- TODO: Refresh projects?
-- TODO: Add take markers
-- TODO: Track newly added plugins (?)
-- TODO: minimal mode (?)