-- @noindex
OD_KeyboardImguiHelperInit = function()
  OD_IMGUI_KEY_NAMES = {
    [ImGui.Mod_Alt] = 'Alt',
    [ImGui.Mod_Ctrl] = _OD_ISMAC and 'Cmd' or 'Ctrl',
    [ImGui.Mod_None] = 'None',
    [ImGui.Mod_Shift] = 'Shift',
    [ImGui.Mod_Super] = _OD_ISMAC and 'Ctrl' or 'Win',
    [ImGui.Key_0] = '0',
    [ImGui.Key_1] = '1',
    [ImGui.Key_2] = '2',
    [ImGui.Key_3] = '3',
    [ImGui.Key_4] = '4',
    [ImGui.Key_5] = '5',
    [ImGui.Key_6] = '6',
    [ImGui.Key_7] = '7',
    [ImGui.Key_8] = '8',
    [ImGui.Key_9] = '9',
    [ImGui.Key_A] = 'A',
    [ImGui.Key_Apostrophe] = '\'',
    [ImGui.Key_AppBack] = 'Back',
    [ImGui.Key_AppForward] = 'Forward',
    [ImGui.Key_B] = 'B',
    [ImGui.Key_Backslash] = '\\',
    [ImGui.Key_Backspace] = 'Backspace',
    [ImGui.Key_C] = 'C',
    [ImGui.Key_CapsLock] = 'Caps Lock',
    [ImGui.Key_Comma] = ',',
    [ImGui.Key_D] = 'D',
    [ImGui.Key_Delete] = 'Delete',
    [ImGui.Key_DownArrow] = 'Down Arrow',
    [ImGui.Key_E] = 'E',
    [ImGui.Key_End] = 'End',
    [ImGui.Key_Enter] = 'Enter',
    [ImGui.Key_Equal] = '=',
    [ImGui.Key_Escape] = 'Esc',
    [ImGui.Key_F] = 'F',
    [ImGui.Key_F1] = 'F1',
    [ImGui.Key_F2] = 'F2',
    [ImGui.Key_F3] = 'F3',
    [ImGui.Key_F4] = 'F4',
    [ImGui.Key_F5] = 'F5',
    [ImGui.Key_F6] = 'F6',
    [ImGui.Key_F7] = 'F7',
    [ImGui.Key_F8] = 'F8',
    [ImGui.Key_F9] = 'F9',
    [ImGui.Key_F10] = 'F10',
    [ImGui.Key_F11] = 'F11',
    [ImGui.Key_F12] = 'F12',
    [ImGui.Key_F13] = 'F13',
    [ImGui.Key_F14] = 'F14',
    [ImGui.Key_F15] = 'F15',
    [ImGui.Key_F16] = 'F16',
    [ImGui.Key_F17] = 'F17',
    [ImGui.Key_F18] = 'F18',
    [ImGui.Key_F19] = 'F19',
    [ImGui.Key_F20] = 'F20',
    [ImGui.Key_F21] = 'F21',
    [ImGui.Key_F22] = 'F22',
    [ImGui.Key_F23] = 'F23',
    [ImGui.Key_F24] = 'F24',
    [ImGui.Key_G] = 'G',
    [ImGui.Key_GraveAccent] = '`',
    [ImGui.Key_H] = 'H',
    [ImGui.Key_Home] = 'Home',
    [ImGui.Key_I] = 'I',
    [ImGui.Key_Insert] = 'Insert',
    [ImGui.Key_J] = 'J',
    [ImGui.Key_K] = 'K',
    [ImGui.Key_Keypad0] = 'Keypad 0',
    [ImGui.Key_Keypad1] = 'Keypad 1',
    [ImGui.Key_Keypad2] = 'Keypad 2',
    [ImGui.Key_Keypad3] = 'Keypad 3',
    [ImGui.Key_Keypad4] = 'Keypad 4',
    [ImGui.Key_Keypad5] = 'Keypad 5',
    [ImGui.Key_Keypad6] = 'Keypad 6',
    [ImGui.Key_Keypad7] = 'Keypad 7',
    [ImGui.Key_Keypad8] = 'Keypad 8',
    [ImGui.Key_Keypad9] = 'Keypad 9',
    [ImGui.Key_KeypadAdd] = 'Keypad +',
    [ImGui.Key_KeypadDecimal] = 'Keypad .',
    [ImGui.Key_KeypadDivide] = 'Keypad /',
    [ImGui.Key_KeypadEnter] = 'Keypad Enter',
    [ImGui.Key_KeypadEqual] = 'Keypad =',
    [ImGui.Key_KeypadMultiply] = 'Keypad *',
    [ImGui.Key_KeypadSubtract] = 'Keypad -',
    [ImGui.Key_L] = 'L',
    [ImGui.Key_LeftAlt] = 'Left Alt',
    [ImGui.Key_LeftArrow] = 'Left Arrow',
    [ImGui.Key_LeftBracket] = 'Left Bracket',
    [ImGui.Key_LeftCtrl] = 'Left Ctrl',
    [ImGui.Key_LeftShift] = 'Left Shift',
    [ImGui.Key_LeftSuper] = 'Left Super',
    [ImGui.Key_M] = 'M',
    [ImGui.Key_Menu] = 'Menu',
    [ImGui.Key_Minus] = 'Minus',
    [ImGui.Key_N] = 'N',
    [ImGui.Key_NumLock] = 'Num Lock',
    [ImGui.Key_O] = 'O',
    [ImGui.Key_P] = 'P',
    [ImGui.Key_PageDown] = 'Page Down',
    [ImGui.Key_PageUp] = 'Page Up',
    [ImGui.Key_Pause] = 'Pause',
    [ImGui.Key_Period] = '.',
    [ImGui.Key_PrintScreen] = 'Print Screen',
    [ImGui.Key_Q] = 'Q',
    [ImGui.Key_R] = 'R',
    [ImGui.Key_RightAlt] = 'Right Alt',
    [ImGui.Key_RightArrow] = 'Right Arrow',
    [ImGui.Key_RightBracket] = 'Right Bracket',
    [ImGui.Key_RightCtrl] = 'Right Ctrl',
    [ImGui.Key_RightShift] = 'Right Shift',
    [ImGui.Key_RightSuper] = 'Right Super',
    [ImGui.Key_S] = 'S',
    [ImGui.Key_ScrollLock] = 'Scroll Lock',
    [ImGui.Key_Semicolon] = ';',
    [ImGui.Key_Slash] = '/',
    [ImGui.Key_Space] = 'Space',
    [ImGui.Key_T] = 'T',
    [ImGui.Key_Tab] = 'Tab',
    [ImGui.Key_U] = 'U',
    [ImGui.Key_UpArrow] = 'Up Arrow',
    [ImGui.Key_V] = 'V',
    [ImGui.Key_W] = 'W',
    [ImGui.Key_X] = 'X',
    [ImGui.Key_Y] = 'Y',
    [ImGui.Key_Z] = 'Z',
  }

  OD_CAPTURABLE_KEYS = {
    ImGui.Key_0,
    ImGui.Key_1,
    ImGui.Key_2,
    ImGui.Key_3,
    ImGui.Key_4,
    ImGui.Key_5,
    ImGui.Key_6,
    ImGui.Key_7,
    ImGui.Key_8,
    ImGui.Key_9,
    ImGui.Key_A,
    ImGui.Key_Apostrophe,
    ImGui.Key_AppBack,
    ImGui.Key_AppForward,
    ImGui.Key_B,
    ImGui.Key_Backslash,
    ImGui.Key_Backspace,
    ImGui.Key_C,
    ImGui.Key_CapsLock,
    ImGui.Key_Comma,
    ImGui.Key_D,
    ImGui.Key_Delete,
    ImGui.Key_DownArrow,
    ImGui.Key_E,
    ImGui.Key_End,
    ImGui.Key_Enter,
    ImGui.Key_Equal,
    ImGui.Key_Escape,
    ImGui.Key_F,
    ImGui.Key_F1,
    ImGui.Key_F2,
    ImGui.Key_F3,
    ImGui.Key_F4,
    ImGui.Key_F5,
    ImGui.Key_F6,
    ImGui.Key_F7,
    ImGui.Key_F8,
    ImGui.Key_F9,
    ImGui.Key_F10,
    ImGui.Key_F11,
    ImGui.Key_F12,
    ImGui.Key_F13,
    ImGui.Key_F14,
    ImGui.Key_F15,
    ImGui.Key_F16,
    ImGui.Key_F17,
    ImGui.Key_F18,
    ImGui.Key_F19,
    ImGui.Key_F20,
    ImGui.Key_F21,
    ImGui.Key_F22,
    ImGui.Key_F23,
    ImGui.Key_F24,
    ImGui.Key_G,
    ImGui.Key_GraveAccent,
    ImGui.Key_H,
    ImGui.Key_Home,
    ImGui.Key_I,
    ImGui.Key_Insert,
    ImGui.Key_J,
    ImGui.Key_K,
    ImGui.Key_Keypad0,
    ImGui.Key_Keypad1,
    ImGui.Key_Keypad2,
    ImGui.Key_Keypad3,
    ImGui.Key_Keypad4,
    ImGui.Key_Keypad5,
    ImGui.Key_Keypad6,
    ImGui.Key_Keypad7,
    ImGui.Key_Keypad8,
    ImGui.Key_Keypad9,
    ImGui.Key_KeypadAdd,
    ImGui.Key_KeypadDecimal,
    ImGui.Key_KeypadDivide,
    ImGui.Key_KeypadEnter,
    ImGui.Key_KeypadEqual,
    ImGui.Key_KeypadMultiply,
    ImGui.Key_KeypadSubtract,
    ImGui.Key_L,
    ImGui.Key_LeftArrow,
    ImGui.Key_LeftBracket,
    ImGui.Key_M,
    ImGui.Key_Minus,
    ImGui.Key_N,
    ImGui.Key_O,
    ImGui.Key_P,
    ImGui.Key_PageDown,
    ImGui.Key_PageUp,
    ImGui.Key_Period,
    ImGui.Key_Q,
    ImGui.Key_R,
    ImGui.Key_RightArrow,
    ImGui.Key_RightBracket,
    ImGui.Key_S,
    ImGui.Key_ScrollLock,
    ImGui.Key_Semicolon,
    ImGui.Key_Slash,
    ImGui.Key_Space,
    ImGui.Key_T,
    ImGui.Key_Tab,
    ImGui.Key_U,
    ImGui.Key_UpArrow,
    ImGui.Key_V,
    ImGui.Key_W,
    ImGui.Key_X,
    ImGui.Key_Y,
    ImGui.Key_Z,
    ImGui.Key_0,
    ImGui.Key_1,
    ImGui.Key_2,
    ImGui.Key_3,
    ImGui.Key_4,
    ImGui.Key_5,
  }

  OD_GetImguiKeysPressed = function(ctx)
    for _, key in ipairs(OD_CAPTURABLE_KEYS) do
      if ImGui.IsKeyDown(ctx, key) then
        return key
      end
    end
  end
end